[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Nimbus"
authors = [{name = "cogniteam", email = "info@cogniteam.com"}]
dynamic = ["version", "description"]
